package juejin.netty.netty.protocol;

public interface Command {

    Byte LOGIN_REQUEST = 1;
    Byte LOGIN_RESPONSE = 2;
    Byte MESSAGE_REQUEST = 3;
    Byte MESSAGE_RESPONSE = 4;

    Byte MESSAGE_TO_USER_REQUEST = 5;
    Byte MESSAGE_FROM_USER_RESPONSE = 6;

    Byte LOGOUT_REQUEST = 7;
    Byte LOGOUT_RESPONSE = 8;
    Byte CREATE_GROUP_REQUEST = 9;
    Byte CREATE_GROUP_RESPONSE = 10;

    Byte JOIN_GROUP_REQUEST = 11;

    Byte JOIN_GROUP_RESPONSE = 12;

    Byte QUIT_GROUP_REQUEST = 13;

    Byte QUIT_GROUP_RESPONSE = 14;

    Byte LIST_GROUP_REQUEST = 15;

    Byte LIST_GROUP_RESPONSE = 16;

    Byte GROUP_MESSAGE_REQUEST = 17;

    Byte GROUP_MESSAGE_RESPONSE = 18;

    Byte HEARTBEAT_REQUEST = 19;
    Byte HEARTBEAT_RESPONSE = 20;

}
